<?php

use Drupal\Core\Form\FormStateInterface;


function custom_module_form_alter(array &$form, FormStateInterface $form_state, $form_id)
{
    // dsm($form_id);
    switch ($form_id) {
        case 'contact_form':
            $form['message']['#required'] = true;
            // insert email
            $form['email'] = array(
                '#type' => 'email',
                '#title' => 'Your email',
                '#weight' => 1, 5
            );
            break;
    }
}

